name: Publish Package to npmjs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@banshan-alec'
      - run: npm ci
      - run: npm pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
